export const CodesError = {
  PUBLIC_ID_INVALID: 'PUBLIC_ID_INVALID',
  NAME_REQUIRED: 'NAME_REQUIRED',
  CODE_INVALID: 'CODE_INVALID',
  EMAIL_INVALID: 'EMAIL_INVALID',
  PHONE_INVALID: 'PHONE_INVALID',
  ROLE_INVALID: 'ROLE_INVALID',
  BRANCH_ID_INVALID: 'BRANCH_ID_INVALID',
  MANAGER_ID_INVALID: 'MANAGER_ID_INVALID',
  OPENED_AT_INVALID: 'OPENED_AT_INVALID',
  HIRED_AT_INVALID: 'HIRED_AT_INVALID',
  IS_ACTIVE_INVALID: 'IS_ACTIVE_INVALID',
} as const;

export type CodesError = (typeof CodesError)[keyof typeof CodesError];
