export const CodesError = {
  DATA_INVALID: 'DATA_INVALID',
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  DUPLICATE_BRANCH: 'DUPLICATE_BRANCH',
  DUPLICATE_BRANCH_CODE: 'DUPLICATE_BRANCH_CODE',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  DUPLICATE_EMPLOYEE: 'DUPLICATE_EMPLOYEE',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  BRANCH_REFERENCE_INVALID: 'BRANCH_REFERENCE_INVALID',
  MANAGER_REFERENCE_INVALID: 'MANAGER_REFERENCE_INVALID',
} as const;

export type CodesError = (typeof CodesError)[keyof typeof CodesError];
